language: python

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: 2.7
    - os: osx
      osx_image: xcode7.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential
  - sudo apt-get install --reinstall binutils

script: python build_ffmpeg.py
